### ISSUE TITLE
VMutableLogicalMatrix getter is called before setter for first item in row. 

### ISSUE THREAD

**Issue by Triscal** [hainayanda/MosaicGrid#3]
Steps to reproduce: 
1. Create a new iOS app in Xcode and add the MosaicGrid package. 
2. Copy the ContentView.swift from the gist into the app. 
3. Run the app in the simulator or on a device. 

Gist: https://gist.github.com/Triscal/d71d77aa50839a26efa97a6f0c14031a

To help with debugging I added a copy of `MutableLogicalMatrix.swift` with two changes, specifically adding extra logging:
Line 33: `log(.info, "Getting matrix bounds [\(column),\(row)] while matrix size is [\(width), \(height)]")`

Line 44: `log(.info, "\(newArrays)")`

The problem is reproducible without the additional logging, the additional logging shows that the setter hasn't run when the first getter runs.

**Comment by Triscal** [comment]
Example log output with the additional logging:
```
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 30: Try to get item out of its matrix bounds. [0,0] while matrix size is [4, 0]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 47: [[false, false, false, false]]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 33: Getting matrix bounds [1,0] while matrix size is [4, 1]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 33: Getting matrix bounds [2,0] while matrix size is [4, 1]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 33: Getting matrix bounds [3,0] while matrix size is [4, 1]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 30: Try to get item out of its matrix bounds. [0,1] while matrix size is [4, 1]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 47: [[false, false, false, false]]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 33: Getting matrix bounds [1,1] while matrix size is [4, 2]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 33: Getting matrix bounds [2,1] while matrix size is [4, 2]
[MosaicGrid] subscript(_:_:) at MosaicGrid/MosaicGrid/Classes/Model/MutableLogicalMatrix.swift line 33: Getting matrix bounds [3,1] while matrix size is [4, 2]
```

**Comment by Triscal** [comment]
I'm new to filing issues on GitHub, if I can be more helpful let me know. :)

**Comment by hainayanda** [comment]
> I'm new to filing issues on GitHub, if I can be more helpful let me know. :) 

You’re already being really helpful, thank you!
Let me check the issue and will get back to you!

**Comment by hainayanda** [comment]
@Triscal I just realized that the code is expected to be called, the issue is because it's logged as an error. I think it better to add another method to check the validity of the index without directly calling the subscript. I'll add a patch.

**Comment by Triscal** [comment]
@hainayanda thanks so much for the updates! 

I was wondering about it, as I got tons of those logs for a larger view with many rows, but everything worked properly so I wasn't sure what the error message was trying to tell me because everything looked perfect.

**Comment by hainayanda** [comment]
@Triscal you can check the [PR](https://github.com/hainayanda/MosaicGrid/pull/4) if you want to know what happening. Basically, while calculating where the view should be put, it will check whether the grid is occupied or not, it was using direct subscript to do this which has a log error when the index is invalid. In this case, when the index is invalid, it means that the mosaic grid should add more rows/columns, so this check was expected, only the error log shouldn't be called.

**Comment by Triscal** [comment]
@hainayanda amazing! Thanks so much for the explanation. It makes sense that it would need to check if an extra row was needed and how that was expected when building the grid you have to add extra rows, but you later on don't want a different item to take up the same space. :) 

My console is so much cleaner now. ❤️
