### ISSUE TITLE
Can you support iOS 14?

### ISSUE THREAD

**Issue by dtrognn** [hainayanda/MosaicGrid#5]
Your package did a great job.  It solved exactly as I expected but unfortunately this package does not support iOS 16 and above.  my app is running with iOS 14, don't know if you can support this.  I have tried several packages with high reviews but did not get the expected results.  Thanks

**Comment by hainayanda** [comment]
> Your package did a great job.  It solved exactly as I expected but unfortunately this package does not support iOS 16 and above.  my app is running with iOS 14, don't know if you can support this.  I have tried several packages with high reviews but did not get the expected results.  Thanks

Let me see what I can do. Actually I forgot why I made this only for iOS 16 and above, I think it's because there's some limitations on iOS 15 and below. Will keep you updated!

**Comment by hainayanda** [comment]
@dtrognn I just checked and realized that it's impossible to support iOS 15 and below since I utilize the Layout, which is only available in iOS 16 and above. The only way to support it is by rewriting the library without using the Layout.

**Comment by hainayanda** [comment]
Supported since v3.0
